#!/usr/bin/python3

import csv, sqlite3
import requests

university_location = open("university-location-city-state.tsv", 'a')

request = "https://maps.googleapis.com/maps/api/geocode/json?address="
api_key = "&key=AIzaSyBIJk5AqilYH8PHt2TP4f5d7QY-UxtJf58"

with open('university-preview.tsv','r') as fin:
    dr = csv.DictReader(fin, dialect="excel-tab")
    id = 0
    for i in dr:
        name = i["Name"]
        response = requests.get(request + name + api_key)
        resp_json_payload = response.json()
        try:
            coordinates = resp_json_payload['results'][0]['geometry']['location']
            lat = coordinates["lat"]
            lon = coordinates["lng"]
            university_location.write(name + '\t' + str(lat) + '\t' + str(lon) + '\t')
            print(name + '\t' + str(lat) + '\t' + str(lon) + '\t', end='')
        except:
            university_location.write(name + '\n')
            print(name, "ERROR: LAT/LON\n")
        try:
            address = resp_json_payload['results'][0]["address_components"]
            for i in address:
                if 'locality' in i['types']:
                    university_location.write(i["short_name"] + '\t')
                    print(i["short_name"] + '\t', end='')
            for i in address:
                if 'administrative_area_level_1' in i['types']:
                    university_location.write(i["short_name"] + '\n')
                    print(i["short_name"] + '\n', end='')
        except:
            university_location.write('\n')
            print(name, "ERROR: CITY/STATE\n")
        id += 1

university_location.close()