#!/usr/bin/python3

import requests
import json
import time

api_keys = ["52e0e0833bcbb8e49f79d81d75fa36d9", "7a2e6121140a43d13d4697bd430bed8a"]

# http://api.linkpreview.net/?key=123456&q=https://www.google.com
api_key = "key=" + api_keys[1] + "&q=https://"

university_domain_existing = open("university-domain-existing.txt", "r")
university_preview = open("university-preview.csv", "a")

university_preview.write("Name,Title,Description,Image,Url\n")

count = 0
start = 60

for line in university_domain_existing:
	if (count >= start) and (count < start + 60):
		name = line[:line.find("(")]
		domain = line[line.find("(")+1:line.find(")")]

		data = api_key + domain
		print(data)
		response = requests.post("https://api.linkpreview.net", data=data)
		preview = response.json()

		title = preview["title"]
		description = preview["description"]
		image = preview["image"]
		url = preview["url"]

		university_preview.write(name + "," + title + "," + description + "," + image + "," + url + "\n")
		print(name + description + "\n")
		time.sleep(3)
	count += 1

university_domain_existing.close()
university_preview.close()