#!/usr/bin/python3

top_universities = open("top-universities.txt", 'r')
all_universities = open("all-universities.txt", 'r')

top_list = []
for line in top_universities:
	top_list.append(line.rstrip('\n'))

all_list = []
for line in all_universities:
	all_list.append(line.rstrip('\n'))

for u in top_list:
	if not u in all_list:
		print(u)

top_universities.close()
all_universities.close()