#!/usr/bin/python3

import csv, sqlite3

con = sqlite3.connect("universities.sqlite3")
cur = con.cursor()
cur.execute("DROP TABLE universities")
cur.execute("CREATE TABLE universities (name, latitude, longitude, city, state, title, description, image, url);")

with open('university-preview.tsv','r') as fin1, open('university-location.tsv', 'r') as fin2:
    dr1 = csv.DictReader(fin1, dialect="excel-tab")
    dr2 = csv.DictReader(fin2, dialect="excel-tab")
    to_db = [(i['Name'], j['Latitude'], j['Longitude'], j['City'], j['State'], i['Title'], i['Description'], i['Image'], i['Url']) for i, j in zip(dr1, dr2)]

cur.executemany("INSERT INTO universities (name, latitude, longitude, city, state, title, description, image, url) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);", to_db)
con.commit()
con.close()